const PRODUCT_DATASHEETS = {
  '3535':      [{ label: 'LINK 3535 — דף נתונים', file: 'attachments/LEDLINK_LINK 3535.pdf' }],
  '3030 \u05e4\u05d9\u05e0\u05ea\u05d9': [{ label: 'LINK 3030 — דף נתונים', file: 'attachments/LEDLINK_LINK 3030.pdf' }],
  '2020':      [{ label: 'LINK 2020 — דף נתונים', file: 'attachments/LEDLINK_LINK 2020.pdf' }],
  '5075':      [{ label: 'LINK 5075N — דף נתונים', file: 'attachments/LEDLINK_LINK 5075N.pdf' }],
  'טיובה 60':  [
    { label: 'LINK R60 — דף נתונים', file: 'attachments/LEDLINK_LINK R60.pdf' },
  ],
  // סטריפ LED — מקוריים (LEDLink)
  "סטריפ LED זיגזג 4.8W": [{ label: "דף קטלוגי — 3D Series", file: "datasheets/3D.pdf" }, { label: "דף נתונים — D", file: "datasheets/DS_3D.pdf" }],
  "סטריפ LED דיגיטלי 24V": [{ label: "דף קטלוגי — ST24560CT", file: "datasheets/ST24560CT.pdf" }, { label: "דף נתונים — T24560CT", file: "datasheets/DS_ST24560CT.pdf" }],
  "סטריפ LED 10W IP20": [{ label: "דף קטלוגי — D24160", file: "datasheets/D24160.pdf" }, { label: "דף נתונים — 24160CT D241610CT", file: "datasheets/DS_D24160CT_D241610CT.pdf" }],
  "סטריפ LED 15W IP20": [{ label: "דף קטלוגי — D24160", file: "datasheets/D24160.pdf" }, { label: "דף נתונים — 24160CT D241610CT", file: "datasheets/DS_D24160CT_D241610CT.pdf" }],
  "סטריפ LED 12W IP65": [{ label: "דף קטלוגי — B24 IP65", file: "datasheets/B24_IP65.pdf" }, { label: "דף נתונים — 24 IP65", file: "datasheets/DS_B24_IP65.pdf" }],
  "סטריפ LED 16W IP65": [{ label: "דף קטלוגי — B24 IP65", file: "datasheets/B24_IP65.pdf" }, { label: "דף נתונים — 24 IP65", file: "datasheets/DS_B24_IP65.pdf" }],
  "סטריפ LED 20W IP65": [{ label: "דף קטלוגי — B24 IP65", file: "datasheets/B24_IP65.pdf" }, { label: "דף נתונים — 24 IP65", file: "datasheets/DS_B24_IP65.pdf" }],
  "סטריפ LED 50W IP20": [{ label: "דף קטלוגי — ST24560CT", file: "datasheets/ST24560CT.pdf" }, { label: "דף נתונים — T24560CT", file: "datasheets/DS_ST24560CT.pdf" }],
  "סטריפ LED DOB 15W IP20": [{ label: "דף קטלוגי — DOB", file: "datasheets/DOB.pdf" }, { label: "דף נתונים — OB", file: "datasheets/DS_DOB.pdf" }],
  "סטריפ LED RGBW 20W IP20": [{ label: "דף קטלוגי — S24120RW", file: "datasheets/S24120RW_S2412ARW.pdf" }, { label: "דף נתונים — 24120RW S2412ARW", file: "datasheets/DS_S24120RW_S2412ARW.pdf" }],
  "סטריפ LED 14.4W IP68": [{ label: "דף קטלוגי — H24 IP68", file: "datasheets/H24_IP68.pdf" }, { label: "דף נתונים — 24 IP68", file: "datasheets/DS_H24_IP68.pdf" }],
  "סטריפ LED 9.6W IP68": [{ label: "דף קטלוגי — H24 IP68", file: "datasheets/H24_IP68.pdf" }, { label: "דף נתונים — 24 IP68", file: "datasheets/DS_H24_IP68.pdf" }],
  "נאון סטריפ LED TOP 14.4W IP67": [{ label: "דף קטלוגי — N2416H", file: "datasheets/N2416H_N2414H1.pdf" }, { label: "דף נתונים — 2416H N2414H", file: "datasheets/DS_N2416H_N2414H.pdf" }],
  "סטריפ LED COB 14.4W IP20": [{ label: "דף קטלוגי — COB", file: "datasheets/COB.pdf" }, { label: "דף נתונים — OB", file: "datasheets/DS_COB.pdf" }],
  "נאון סטריפ LED SIDE 18W IP67": [{ label: "דף קטלוגי — N2412L", file: "datasheets/N2412L.pdf" }, { label: "דף נתונים — 2412L", file: "datasheets/DS_N2412L.pdf" }],
  "סטריפ LED RGB IP67 14.4W": [{ label: "דף קטלוגי — N2412B0RG", file: "datasheets/N2412B0RG.pdf" }, { label: "דף נתונים — 2412BRG", file: "datasheets/DS_N2412BRG.pdf" }],
  "סטריפ LED RGBW 20W IP65": [{ label: "דף קטלוגי — S24120RW", file: "datasheets/S24120RW_S2412ARW.pdf" }, { label: "דף נתונים — 24120RW S2412ARW", file: "datasheets/DS_S24120RW_S2412ARW.pdf" }],
  // סטריפ LED — QLT
  "3D2460": [{ label: "דף קטלוגי — 3D", file: "datasheets/3D.pdf" }, { label: "דף נתונים — D", file: "datasheets/DS_3D.pdf" }],
  "A24112": [{ label: "דף קטלוגי — A24 FOOD", file: "datasheets/A24_FOOD.pdf" }, { label: "דף נתונים — 24 FOOD", file: "datasheets/DS_A24_FOOD.pdf" }],
  "A2411C": [{ label: "דף קטלוגי — A24 CRI95 IP20", file: "datasheets/A24_CRI95_IP20.pdf" }, { label: "דף נתונים — 24C IP20", file: "datasheets/DS_A24C_IP20.pdf" }],
  "A2411CA": [{ label: "דף קטלוגי — A24 CRI95 IP65", file: "datasheets/A24_CRI95_IP65.pdf" }, { label: "דף נתונים — 24CA IP65", file: "datasheets/DS_A24CA_IP65.pdf" }],
  "A2411CI": [{ label: "דף קטלוגי — A24 CRI95 IP68", file: "datasheets/A24_CRI95_IP68.pdf" }, { label: "דף נתונים — 24CI IP68", file: "datasheets/DS_A24CI_IP68.pdf" }],
  "A2416C": [{ label: "דף קטלוגי — A24 CRI95 IP20", file: "datasheets/A24_CRI95_IP20.pdf" }, { label: "דף נתונים — 24C IP20", file: "datasheets/DS_A24C_IP20.pdf" }],
  "A2416CA": [{ label: "דף קטלוגי — A24 CRI95 IP65", file: "datasheets/A24_CRI95_IP65.pdf" }, { label: "דף נתונים — 24CA IP65", file: "datasheets/DS_A24CA_IP65.pdf" }],
  "A2416CI": [{ label: "דף קטלוגי — A24 CRI95 IP68", file: "datasheets/A24_CRI95_IP68.pdf" }, { label: "דף נתונים — 24CI IP68", file: "datasheets/DS_A24CI_IP68.pdf" }],
  "A2424C": [{ label: "דף קטלוגי — A24 CRI95 IP20", file: "datasheets/A24_CRI95_IP20.pdf" }, { label: "דף נתונים — 24C IP20", file: "datasheets/DS_A24C_IP20.pdf" }],
  "A2424CA": [{ label: "דף קטלוגי — A24 CRI95 IP65", file: "datasheets/A24_CRI95_IP65.pdf" }],
  "B24080": [{ label: "דף קטלוגי — B24 IP20", file: "datasheets/B24_IP20.pdf" }, { label: "דף נתונים — 24 IP20", file: "datasheets/DS_B24_IP20.pdf" }],
  "B24080A": [{ label: "דף קטלוגי — B24 IP65", file: "datasheets/B24_IP65.pdf" }, { label: "דף נתונים — 24 IP65", file: "datasheets/DS_B24_IP65.pdf" }],
  "B24128": [{ label: "דף קטלוגי — B24 IP20", file: "datasheets/B24_IP20.pdf" }, { label: "דף נתונים — 24 IP20", file: "datasheets/DS_B24_IP20.pdf" }],
  "B24128A": [{ label: "דף קטלוגי — B24 IP65", file: "datasheets/B24_IP65.pdf" }, { label: "דף נתונים — 24 IP65", file: "datasheets/DS_B24_IP65.pdf" }],
  "B24160": [{ label: "דף קטלוגי — B24 IP20", file: "datasheets/B24_IP20.pdf" }, { label: "דף נתונים — 24 IP20", file: "datasheets/DS_B24_IP20.pdf" }],
  "B24160A": [{ label: "דף קטלוגי — B24 IP65", file: "datasheets/B24_IP65.pdf" }, { label: "דף נתונים — 24 IP65", file: "datasheets/DS_B24_IP65.pdf" }],
  "COB2488": [{ label: "דף קטלוגי — COB", file: "datasheets/COB.pdf" }, { label: "דף נתונים — OB", file: "datasheets/DS_COB.pdf" }],
  "COB2L15": [{ label: "דף קטלוגי — COB", file: "datasheets/COB.pdf" }, { label: "דף נתונים — OB", file: "datasheets/DS_COB.pdf" }],
  "COB845A": [{ label: "דף קטלוגי — COB845A", file: "datasheets/COB845A.pdf" }, { label: "דף נתונים — OB845A", file: "datasheets/DS_COB845A.pdf" }],
  "D241600CT": [{ label: "דף קטלוגי — D24160CT D241610CT", file: "datasheets/D24160CT_D241610CT.pdf" }, { label: "דף נתונים — 24160CT D241610CT", file: "datasheets/DS_D24160CT_D241610CT.pdf" }],
  "D241608": [{ label: "דף קטלוגי — D24160", file: "datasheets/D24160.pdf" }, { label: "דף נתונים — 24160", file: "datasheets/DS_D24160.pdf" }],
  "D241610": [{ label: "דף נתונים — 24160", file: "datasheets/DS_D24160.pdf" }],
  "D241610CT": [{ label: "דף קטלוגי — D24160CT D241610CT", file: "datasheets/D24160CT_D241610CT.pdf" }, { label: "דף נתונים — 24160CT D241610CT", file: "datasheets/DS_D24160CT_D241610CT.pdf" }],
  "D241615": [{ label: "דף קטלוגי — D24160", file: "datasheets/D24160.pdf" }, { label: "דף נתונים — 24160", file: "datasheets/DS_D24160.pdf" }],
  "D242006": [{ label: "דף קטלוגי — D24200", file: "datasheets/D24200.pdf" }, { label: "דף נתונים — 24200", file: "datasheets/DS_D24200.pdf" }],
  "D242008": [{ label: "דף קטלוגי — D24200", file: "datasheets/D24200.pdf" }, { label: "דף נתונים — 24200", file: "datasheets/DS_D24200.pdf" }],
  "D242011": [{ label: "דף קטלוגי — D24200", file: "datasheets/D24200.pdf" }, { label: "דף נתונים — 24200", file: "datasheets/DS_D24200.pdf" }],
  "DOB2428": [{ label: "דף קטלוגי — DOB", file: "datasheets/DOB.pdf" }, { label: "דף נתונים — OB", file: "datasheets/DS_DOB.pdf" }],
  "DOB2432 TW": [{ label: "דף קטלוגי — DOBTW", file: "datasheets/DOBTW.pdf" }, { label: "דף נתונים — OB TW", file: "datasheets/DS_DOB_TW.pdf" }],
  "DOB2433 RGB+W": [{ label: "דף קטלוגי — DOBRGBW", file: "datasheets/DOBRGBW.pdf" }, { label: "דף נתונים — OB RGBW", file: "datasheets/DS_DOB_RGBW.pdf" }],
  "DOBG288": [{ label: "דף קטלוגי — DOBGOLD", file: "datasheets/DOBGOLD.pdf" }, { label: "דף נתונים — OB GOLD", file: "datasheets/DS_DOB_GOLD.pdf" }],
  "DW242027W": [{ label: "דף קטלוגי — DW", file: "datasheets/DW.pdf" }, { label: "דף נתונים — W", file: "datasheets/DS_DW.pdf" }],
  "ES24120": [{ label: "דף קטלוגי — ES24", file: "datasheets/ES24.pdf" }, { label: "דף נתונים — S IP20", file: "datasheets/DS_ES_IP20.pdf" }],
  "ES24180": [{ label: "דף קטלוגי — ES24", file: "datasheets/ES24.pdf" }, { label: "דף נתונים — S IP20", file: "datasheets/DS_ES_IP20.pdf" }],
  "ES24240": [{ label: "דף קטלוגי — ES24", file: "datasheets/ES24.pdf" }, { label: "דף נתונים — S IP20", file: "datasheets/DS_ES_IP20.pdf" }],
  "ES2460": [{ label: "דף קטלוגי — ES24", file: "datasheets/ES24.pdf" }, { label: "דף נתונים — S IP20", file: "datasheets/DS_ES_IP20.pdf" }],
  "F241445": [{ label: "דף קטלוגי — F24 4mm", file: "datasheets/F24_4mm.pdf" }, { label: "דף נתונים — 24 140 180 210", file: "datasheets/DS_F24_140_180_210.pdf" }],
  "F241811": [{ label: "דף קטלוגי — F24 4mm", file: "datasheets/F24_4mm.pdf" }, { label: "דף נתונים — 24 140 180 210", file: "datasheets/DS_F24_140_180_210.pdf" }],
  "F241820": [{ label: "דף קטלוגי — F24 8mm", file: "datasheets/F24_8mm.pdf" }, { label: "דף נתונים — 241820", file: "datasheets/DS_F241820.pdf" }],
  "F242108": [{ label: "דף קטלוגי — F24 4mm", file: "datasheets/F24_4mm.pdf" }, { label: "דף נתונים — 24 140 180 210", file: "datasheets/DS_F24_140_180_210.pdf" }],
  "H12060": [{ label: "דף קטלוגי — H12 IP20", file: "datasheets/H12_IP20.pdf" }, { label: "דף נתונים — 12 IP20", file: "datasheets/DS_H12_IP20.pdf" }],
  "H12060A": [{ label: "דף קטלוגי — H12 IP65", file: "datasheets/H12_IP65.pdf" }, { label: "דף נתונים — 12 IP65", file: "datasheets/DS_H12_IP65.pdf" }],
  "H12120": [{ label: "דף קטלוגי — H12 IP20", file: "datasheets/H12_IP20.pdf" }, { label: "דף נתונים — 12 IP20", file: "datasheets/DS_H12_IP20.pdf" }],
  "H12120A": [{ label: "דף קטלוגי — H12 IP65", file: "datasheets/H12_IP65.pdf" }, { label: "דף נתונים — 12 IP65", file: "datasheets/DS_H12_IP65.pdf" }],
  "H24070": [{ label: "דף נתונים — 24 IP20", file: "datasheets/DS_H24_IP20.pdf" }],
  "H24070A": [{ label: "דף קטלוגי — H24 IP65", file: "datasheets/H24_IP65.pdf" }, { label: "דף נתונים — 24 IP65", file: "datasheets/DS_H24_IP65.pdf" }],
  "H24070I": [{ label: "דף קטלוגי — H24 IP68", file: "datasheets/H24_IP68.pdf" }, { label: "דף נתונים — 24 IP68", file: "datasheets/DS_H24_IP68.pdf" }],
  "H24140": [{ label: "דף קטלוגי — H24 IP20", file: "datasheets/H24_IP20.pdf" }, { label: "דף נתונים — 24 IP20", file: "datasheets/DS_H24_IP20.pdf" }],
  "H24140A": [{ label: "דף קטלוגי — H24 IP65", file: "datasheets/H24_IP65.pdf" }, { label: "דף נתונים — 24 IP65", file: "datasheets/DS_H24_IP65.pdf" }],
  "H24140I": [{ label: "דף קטלוגי — H24 IP68", file: "datasheets/H24_IP68.pdf" }, { label: "דף נתונים — 24 IP68", file: "datasheets/DS_H24_IP68.pdf" }],
  "H24210": [{ label: "דף קטלוגי — H24 IP20", file: "datasheets/H24_IP20.pdf" }, { label: "דף נתונים — 24 IP20", file: "datasheets/DS_H24_IP20.pdf" }],
  "H24210A": [{ label: "דף קטלוגי — H24 IP65", file: "datasheets/H24_IP65.pdf" }, { label: "דף נתונים — 24 IP65", file: "datasheets/DS_H24_IP65.pdf" }],
  "H24210I": [{ label: "דף קטלוגי — H24 IP68", file: "datasheets/H24_IP68.pdf" }, { label: "דף נתונים — 24 IP68", file: "datasheets/DS_H24_IP68.pdf" }],
  "H24252": [{ label: "דף קטלוגי — H24 IP20", file: "datasheets/H24_IP20.pdf" }],
  "H48140": [{ label: "דף קטלוגי — H48 IP20", file: "datasheets/H48_IP20.pdf" }, { label: "דף נתונים — 48 IP20", file: "datasheets/DS_H48_IP20.pdf" }],
  "H48140A": [{ label: "דף קטלוגי — H48 IP65", file: "datasheets/H48_IP65.pdf" }, { label: "דף נתונים — 48 IP65", file: "datasheets/DS_H48_IP65.pdf" }],
  "HV07250": [{ label: "דף קטלוגי — HV", file: "datasheets/HV.pdf" }, { label: "דף נתונים — V", file: "datasheets/DS_HV.pdf" }],
  "K24120": [{ label: "דף קטלוגי — K24120 160 200 240 IP20", file: "datasheets/K24120_160_200_240_IP20.pdf" }, { label: "דף נתונים — 24120 160 200 240 IP20", file: "datasheets/DS_K24120_160_200_240_IP20.pdf" }],
  "K24120A": [{ label: "דף קטלוגי — K24120 160 200 240 IP65", file: "datasheets/K24120_160_200_240_IP65.pdf" }, { label: "דף נתונים — 24120 160 200 240 IP65", file: "datasheets/DS_K24120_160_200_240_IP65.pdf" }],
  "K24160": [{ label: "דף קטלוגי — K24120 160 200 240 IP20", file: "datasheets/K24120_160_200_240_IP20.pdf" }, { label: "דף נתונים — 24120 160 200 240 IP20", file: "datasheets/DS_K24120_160_200_240_IP20.pdf" }],
  "K24160A": [{ label: "דף קטלוגי — K24120 160 200 240 IP65", file: "datasheets/K24120_160_200_240_IP65.pdf" }, { label: "דף נתונים — 24120 160 200 240 IP65", file: "datasheets/DS_K24120_160_200_240_IP65.pdf" }],
  "K24200": [{ label: "דף קטלוגי — K24120 160 200 240 IP20", file: "datasheets/K24120_160_200_240_IP20.pdf" }, { label: "דף נתונים — 24120 160 200 240 IP20", file: "datasheets/DS_K24120_160_200_240_IP20.pdf" }],
  "K24200A": [{ label: "דף קטלוגי — K24120 160 200 240 IP65", file: "datasheets/K24120_160_200_240_IP65.pdf" }, { label: "דף נתונים — 24120 160 200 240 IP65", file: "datasheets/DS_K24120_160_200_240_IP65.pdf" }],
  "K24240": [{ label: "דף קטלוגי — K24120 160 200 240 IP20", file: "datasheets/K24120_160_200_240_IP20.pdf" }, { label: "דף נתונים — 24120 160 200 240 IP20", file: "datasheets/DS_K24120_160_200_240_IP20.pdf" }],
  "K24240A": [{ label: "דף קטלוגי — K24120 160 200 240 IP65", file: "datasheets/K24120_160_200_240_IP65.pdf" }, { label: "דף נתונים — 24120 160 200 240 IP65", file: "datasheets/DS_K24120_160_200_240_IP65.pdf" }],
  "N2412B0RG": [{ label: "דף קטלוגי — N2412B0RG", file: "datasheets/N2412B0RG.pdf" }, { label: "דף נתונים — 2412BRG", file: "datasheets/DS_N2412BRG.pdf" }],
  "N2412B1RG": [{ label: "דף קטלוגי — N2412B0RG", file: "datasheets/N2412B0RG.pdf" }, { label: "דף נתונים — 2412BRG", file: "datasheets/DS_N2412BRG.pdf" }],
  "N2412F": [{ label: "דף קטלוגי — N2412F", file: "datasheets/N2412F.pdf" }, { label: "דף נתונים — 2412F", file: "datasheets/DS_N2412F.pdf" }],
  "N2412L": [{ label: "דף קטלוגי — N2412L", file: "datasheets/N2412L.pdf" }, { label: "דף נתונים — 2412L", file: "datasheets/DS_N2412L.pdf" }],
  "N2414H0RG": [{ label: "דף קטלוגי — N2414HRG", file: "datasheets/N2414HRG.pdf" }, { label: "דף נתונים — 2414H0RG N2414H1RG", file: "datasheets/DS_N2414H0RG_N2414H1RG.pdf" }],
  "N2414H1": [{ label: "דף קטלוגי — N2416H N2414H1", file: "datasheets/N2416H_N2414H1.pdf" }, { label: "דף נתונים — 2416H N2414H", file: "datasheets/DS_N2416H_N2414H.pdf" }],
  "N2414H1RG": [{ label: "דף קטלוגי — N2414HRG", file: "datasheets/N2414HRG.pdf" }, { label: "דף נתונים — 2414H0RG N2414H1RG", file: "datasheets/DS_N2414H0RG_N2414H1RG.pdf" }],
  "N2416H": [{ label: "דף קטלוגי — N2416H N2414H1", file: "datasheets/N2416H_N2414H1.pdf" }, { label: "דף נתונים — 2416H N2414H", file: "datasheets/DS_N2416H_N2414H.pdf" }],
  "N3X8 MINI NEON": [{ label: "דף קטלוגי — N03X08", file: "datasheets/N03X08.pdf" }, { label: "דף נתונים — 0308", file: "datasheets/DS_N0308.pdf" }],
  "N4x10": [{ label: "דף קטלוגי — N0410", file: "datasheets/N0410.pdf" }, { label: "דף נתונים — 0410", file: "datasheets/DS_N0410.pdf" }],
  "N4X10T": [{ label: "דף קטלוגי — N04X10T", file: "datasheets/N04X10T.pdf" }, { label: "דף נתונים — 0410T", file: "datasheets/DS_N0410T.pdf" }],
  "N8X8 NEON 3D": [{ label: "דף קטלוגי — N08X08", file: "datasheets/N08X08.pdf" }, { label: "דף נתונים — 0808", file: "datasheets/DS_N0808.pdf" }],
  "NP2436834": [{ label: "דף קטלוגי — NP", file: "datasheets/NP.pdf" }, { label: "דף נתונים — P", file: "datasheets/DS_NP.pdf" }],
  "NT1811 360° strip NEON LED TUBE": [{ label: "דף קטלוגי — NT18 23", file: "datasheets/NT18_23.pdf" }, { label: "דף נתונים — T1811 2314", file: "datasheets/DS_NT1811_2314.pdf" }],
  "NT2314 360° strip NEON LED TUBE": [{ label: "דף קטלוגי — NT18 23", file: "datasheets/NT18_23.pdf" }, { label: "דף נתונים — T1811 2314", file: "datasheets/DS_NT1811_2314.pdf" }],
  "NTR2416 NEON TRIANGLE": [{ label: "דף קטלוגי — NTR24", file: "datasheets/NTR24.pdf" }, { label: "דף נתונים — TR24", file: "datasheets/DS_NTR24.pdf" }],
  "S24120RW": [{ label: "דף קטלוגי — S24120RW S2412ARW", file: "datasheets/S24120RW_S2412ARW.pdf" }, { label: "דף נתונים — 24120RW S2412ARW", file: "datasheets/DS_S24120RW_S2412ARW.pdf" }],
  "S2412ARW": [{ label: "דף קטלוגי — S24120RW S2412ARW", file: "datasheets/S24120RW_S2412ARW.pdf" }, { label: "דף נתונים — 24120RW S2412ARW", file: "datasheets/DS_S24120RW_S2412ARW.pdf" }],
  "SPI COB RGB+W": [{ label: "דף קטלוגי — SPICOBRGBW", file: "datasheets/SPICOBRGBW.pdf" }, { label: "דף נתונים — PICOB RGBW", file: "datasheets/DS_SPICOB_RGBW.pdf" }],
  "SPI NEON RGB+W": [{ label: "דף קטלוגי — SPIN12RW3", file: "datasheets/SPIN12RW3.pdf" }, { label: "דף נתונים — PIN12RW3", file: "datasheets/DS_SPIN12RW3.pdf" }],
  "SPI NEON WH": [{ label: "דף קטלוגי — SPIN12", file: "datasheets/SPIN12.pdf" }, { label: "דף נתונים — PIN12", file: "datasheets/DS_SPIN12.pdf" }],
  "SPI WH": [{ label: "דף קטלוגי — SPI140", file: "datasheets/SPI140.pdf" }, { label: "דף נתונים — PI140", file: "datasheets/DS_SPI140.pdf" }],
  "ST241120R": [{ label: "דף קטלוגי — ST24112R ST24112AR", file: "datasheets/ST24112R_ST24112AR.pdf" }, { label: "דף נתונים — T24112R ST24112AR", file: "datasheets/DS_ST24112R_ST24112AR.pdf" }],
  "ST24112AR": [{ label: "דף קטלוגי — ST24112R ST24112AR", file: "datasheets/ST24112R_ST24112AR.pdf" }, { label: "דף נתונים — T24112R ST24112AR", file: "datasheets/DS_ST24112R_ST24112AR.pdf" }],
  "ST241200R": [{ label: "דף קטלוגי — ST24120R ST24120AR", file: "datasheets/ST24120R_ST24120AR.pdf" }, { label: "דף נתונים — T24120R ST24120AR", file: "datasheets/DS_ST24120R_ST24120AR.pdf" }],
  "ST24120AR": [{ label: "דף קטלוגי — ST24120R ST24120AR", file: "datasheets/ST24120R_ST24120AR.pdf" }, { label: "דף נתונים — T24120R ST24120AR", file: "datasheets/DS_ST24120R_ST24120AR.pdf" }],
  "ST24560CT": [{ label: "דף קטלוגי — ST24560CT", file: "datasheets/ST24560CT.pdf" }, { label: "דף נתונים — T24560CT", file: "datasheets/DS_ST24560CT.pdf" }],
  "ST24600RG": [{ label: "דף קטלוגי — ST2460RG ST2460ASR ST2460ISR", file: "datasheets/ST2460RG_ST2460ASR_ST2460ISR.pdf" }, { label: "דף נתונים — T2460RG ST2460ASR ST2460ISR", file: "datasheets/DS_ST2460RG_ST2460ASR_ST2460ISR.pdf" }],
  "ST2460ASR": [{ label: "דף קטלוגי — ST2460RG ST2460ASR ST2460ISR", file: "datasheets/ST2460RG_ST2460ASR_ST2460ISR.pdf" }, { label: "דף נתונים — T2460RG ST2460ASR ST2460ISR", file: "datasheets/DS_ST2460RG_ST2460ASR_ST2460ISR.pdf" }],
  "ST2460ISR": [{ label: "דף קטלוגי — ST2460RG ST2460ASR ST2460ISR", file: "datasheets/ST2460RG_ST2460ASR_ST2460ISR.pdf" }, { label: "דף נתונים — T2460RG ST2460ASR ST2460ISR", file: "datasheets/DS_ST2460RG_ST2460ASR_ST2460ISR.pdf" }],
  // דרייברים QLT
  "BK100": [{ label: "דף קטלוגי — BK", file: "datasheets/BK.pdf" }, { label: "דף נתונים — BK", file: "datasheets/DS_BK.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_BK.pdf" }],
  "BPS2": [{ label: "דף קטלוגי — BPS", file: "datasheets/BPS.pdf" }, { label: "דף נתונים — BPS", file: "datasheets/DS_BPS.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_BPS.pdf" }],
  "BPS3": [{ label: "דף קטלוגי — BPS", file: "datasheets/BPS.pdf" }, { label: "דף נתונים — BPS", file: "datasheets/DS_BPS.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_BPS.pdf" }],
  "BRICK060": [{ label: "דף קטלוגי — BRICK", file: "datasheets/BRICK.pdf" }, { label: "דף נתונים — BRICK", file: "datasheets/DS_BRICK.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "BRICK100": [{ label: "דף קטלוגי — BRICK", file: "datasheets/BRICK.pdf" }, { label: "דף נתונים — BRICK", file: "datasheets/DS_BRICK.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "BRICK150": [{ label: "דף קטלוגי — BRICK", file: "datasheets/BRICK.pdf" }, { label: "דף נתונים — BRICK", file: "datasheets/DS_BRICK.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "CC23W MULTICURRENT ON/OFF": [{ label: "דף קטלוגי — CC", file: "datasheets/CC.pdf" }, { label: "דף נתונים — CC", file: "datasheets/DS_CC.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_CC.pdf" }],
  "CC23WD MULTICURRENT DALI/PUSH DIMMABLE": [{ label: "דף קטלוגי — CCD", file: "datasheets/CCD.pdf" }, { label: "דף נתונים — CCD", file: "datasheets/DS_CCD.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_CC.pdf" }],
  "CC36W MULTICURRENT ON/OFF": [{ label: "דף קטלוגי — CC", file: "datasheets/CC.pdf" }, { label: "דף נתונים — CC", file: "datasheets/DS_CC.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_CC.pdf" }],
  "CC36WD MULTICURRENT DALI/PUSH DIMMABLE": [{ label: "דף קטלוגי — CCD", file: "datasheets/CCD.pdf" }, { label: "דף נתונים — CCD", file: "datasheets/DS_CCD.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_CC.pdf" }],
  "CC44W MULTICURRENT ON/OFF": [{ label: "דף קטלוגי — CC", file: "datasheets/CC.pdf" }, { label: "דף נתונים — CC", file: "datasheets/DS_CC.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_CC.pdf" }],
  "CC44WD MULTICURRENT DALI/PUSH DIMMABLE": [{ label: "דף קטלוגי — CCD", file: "datasheets/CCD.pdf" }, { label: "דף נתונים — CCD", file: "datasheets/DS_CCD.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_CC.pdf" }],
  "CC60W MULTICURRENT ON/OFF": [{ label: "דף קטלוגי — CC", file: "datasheets/CC.pdf" }, { label: "דף נתונים — CC", file: "datasheets/DS_CC.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_CC.pdf" }],
  "CC60WD MULTICURRENT DALI/PUSH/1": [{ label: "דף קטלוגי — CCD", file: "datasheets/CCD.pdf" }, { label: "דף נתונים — CCD", file: "datasheets/DS_CCD.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_CC.pdf" }],
  "CCBXH60 MULTICURRENT": [{ label: "דף קטלוגי — CCBX", file: "datasheets/CCBX.pdf" }, { label: "דף נתונים — CCBX", file: "datasheets/DS_CCBX.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_CCBX.pdf" }],
  "CCBXH60D MULTICURRENT DALI/PUSH DIMMABLE": [{ label: "דף קטלוגי — CCBXD", file: "datasheets/CCBXD.pdf" }, { label: "דף נתונים — CCBXD", file: "datasheets/DS_CCBXD.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_CCBXD.pdf" }],
  "CCBXL60 MULTICURRENT ON/OFF": [{ label: "דף קטלוגי — CCBX", file: "datasheets/CCBX.pdf" }, { label: "דף נתונים — CCBX", file: "datasheets/DS_CCBX.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_CCBXH.pdf" }],
  "CCBXL60D MULTICURRENT DALI/PUSH DIMMABLE": [{ label: "דף קטלוגי — CCBXD", file: "datasheets/CCBXD.pdf" }, { label: "דף נתונים — CCBXD", file: "datasheets/DS_CCBXD.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_CCBXD.pdf" }],
  "CE017 DIMMABLE": [{ label: "דף קטלוגי — CE", file: "datasheets/CE.pdf" }, { label: "דף נתונים — CE", file: "datasheets/DS_CE.pdf" }],
  "CE030 DIMMABLE": [{ label: "דף קטלוגי — CE", file: "datasheets/CE.pdf" }, { label: "דף נתונים — CE", file: "datasheets/DS_CE.pdf" }],
  "CPL112": [{ label: "דף קטלוגי — CPL", file: "datasheets/CPL.pdf" }, { label: "דף נתונים — CPL", file: "datasheets/DS_CPL.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "CPL206": [{ label: "דף קטלוגי — CPL", file: "datasheets/CPL.pdf" }, { label: "דף נתונים — CPL", file: "datasheets/DS_CPL.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "CPL306": [{ label: "דף קטלוגי — CPL", file: "datasheets/CPL.pdf" }, { label: "דף נתונים — CPL", file: "datasheets/DS_CPL.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "CV23W": [{ label: "דף קטלוגי — CV", file: "datasheets/CV.pdf" }, { label: "דף נתונים — CV", file: "datasheets/DS_CV.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_CV_CVD.pdf" }],
  "CV36W": [{ label: "דף קטלוגי — CV", file: "datasheets/CV.pdf" }, { label: "דף נתונים — CV", file: "datasheets/DS_CV.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_CV_CVD.pdf" }],
  "CV36WD Dimmable": [{ label: "דף קטלוגי — CVD", file: "datasheets/CVD.pdf" }, { label: "דף נתונים — CVD", file: "datasheets/DS_CVD.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_CV_CVD.pdf" }],
  "DALI1103 DIMMABLE INTERFACE": [{ label: "דף קטלוגי — DALI1103", file: "datasheets/DALI1103.pdf" }, { label: "דף נתונים — DALI1103", file: "datasheets/DS_DALI1103.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_DALI1103.pdf" }],
  "DALICUBE 48V DIMMABLE INTERFACE": [{ label: "דף קטלוגי — DALICUBE48", file: "datasheets/DALICUBE48.pdf" }, { label: "דף נתונים — DACUBE 48V", file: "datasheets/DS_DACUBE_48V.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_DALICUBE.pdf" }],
  "DAPUSH2 DALI PUSH/TIMER": [{ label: "דף קטלוגי — DAPUSH2", file: "datasheets/DAPUSH2.pdf" }, { label: "דף נתונים — DAPUSH2", file: "datasheets/DS_DAPUSH2.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_DAPUSH2.pdf" }],
  "DASE2": [{ label: "דף קטלוגי — DASE2", file: "datasheets/DASE2.pdf" }, { label: "דף נתונים — DASE2", file: "datasheets/DS_DASE2.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_DASE2B.pdf" }],
  "DASE3 Sensore PIR Broadcast": [{ label: "דף קטלוגי — DASE3", file: "datasheets/DASE3.pdf" }, { label: "דף נתונים — DASE3", file: "datasheets/DS_DASE3.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_DASE3.pdf" }],
  "DBOX35 DIMMABLE": [{ label: "דף קטלוגי — DBOX", file: "datasheets/DBOX.pdf" }, { label: "דף נתונים — DBOX", file: "datasheets/DS_DBOX.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_DBOX.pdf" }],
  "DDMASTER": [{ label: "דף קטלוגי — DDMASTER", file: "datasheets/DDMASTER.pdf" }, { label: "דף נתונים — DDMASTER", file: "datasheets/DS_DDMASTER.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_DDMASTER.pdf" }],
  "DIMCUBE 24V DIMMABLE INTERFACE": [{ label: "דף קטלוגי — DIMCUBE24", file: "datasheets/DIMCUBE24.pdf" }, { label: "דף נתונים — DIMCUBE24", file: "datasheets/DS_DIMCUBE24.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_DIMCUBE24.pdf" }],
  "DIN080 DIN": [{ label: "דף קטלוגי — DIN80 DIN160", file: "datasheets/DIN80_DIN160.pdf" }, { label: "דף נתונים — DIN80 DIN160", file: "datasheets/DS_DIN80_DIN160.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_DIN80_DIN160.pdf" }],
  "DIN160 DIN": [{ label: "דף קטלוגי — DIN80 DIN160", file: "datasheets/DIN80_DIN160.pdf" }, { label: "דף נתונים — DIN80 DIN160", file: "datasheets/DS_DIN80_DIN160.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_DIN80_DIN160.pdf" }],
  "DMX203  INTERFACE": [{ label: "דף קטלוגי — DMX203", file: "datasheets/DMX203.pdf" }, { label: "דף נתונים — DMX203", file: "datasheets/DS_DMX203.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_DMX203.pdf" }],
  "DMX220": [{ label: "דף קטלוגי — DMX220", file: "datasheets/DMX220.pdf" }, { label: "דף נתונים — DMX220", file: "datasheets/DS_DMX220.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_DMX200_220.pdf" }],
  "DMXDALI 1  INTERFACE": [{ label: "דף קטלוגי — DMXDALI1", file: "datasheets/DMXDALI1.pdf" }, { label: "דף נתונים — DMXDALI1", file: "datasheets/DS_DMXDALI1.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_DMXDALI1.pdf" }],
  "DPL110E": [{ label: "דף קטלוגי — DPL", file: "datasheets/DPL.pdf" }, { label: "דף נתונים — DPL", file: "datasheets/DS_DPL.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "FB036": [{ label: "דף קטלוגי — FB", file: "datasheets/FB.pdf" }, { label: "דף נתונים — FB", file: "datasheets/DS_FB.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "FB060": [{ label: "דף קטלוגי — FB", file: "datasheets/FB.pdf" }, { label: "דף נתונים — FB", file: "datasheets/DS_FB.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "FB060 0": [{ label: "דף קטלוגי — FBD", file: "datasheets/FBD.pdf" }, { label: "דף נתונים — FBD", file: "datasheets/DS_FBD.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_FBD.pdf" }],
  "FB060 1": [{ label: "דף קטלוגי — FBD", file: "datasheets/FBD.pdf" }, { label: "דף נתונים — FBD", file: "datasheets/DS_FBD.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_FBD.pdf" }],
  "FLAT112": [{ label: "דף קטלוגי — FLAT", file: "datasheets/FLAT.pdf" }, { label: "דף נתונים — FLAT", file: "datasheets/DS_FLAT.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "FLAT12": [{ label: "דף קטלוגי — FLAT", file: "datasheets/FLAT.pdf" }, { label: "דף נתונים — FLAT", file: "datasheets/DS_FLAT.pdf" }],
  "FLAT30": [{ label: "דף קטלוגי — FLAT", file: "datasheets/FLAT.pdf" }, { label: "דף נתונים — FLAT", file: "datasheets/DS_FLAT.pdf" }],
  "FLAT306": [{ label: "דף קטלוגי — FLAT", file: "datasheets/FLAT.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "FLO 24 DIMMABLE": [{ label: "דף קטלוגי — FLO", file: "datasheets/FLO.pdf" }, { label: "דף נתונים — FLO", file: "datasheets/DS_FLO.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_FLO.pdf" }],
  "IDNDP010 DIN": [{ label: "דף קטלוגי — IDNDP", file: "datasheets/IDNDP.pdf" }, { label: "דף נתונים — IDNDP", file: "datasheets/DS_IDNDP.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_IDNDP.pdf" }],
  "IDNDP110 DIN": [{ label: "דף קטלוגי — IDNDP", file: "datasheets/IDNDP.pdf" }, { label: "דף נתונים — IDNDP", file: "datasheets/DS_IDNDP.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_IDNDP.pdf" }],
  "LVB250": [{ label: "דף קטלוגי — LVB", file: "datasheets/LVB.pdf" }, { label: "דף נתונים — LVB", file: "datasheets/DS_LVB.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "LVB350": [{ label: "דף קטלוגי — LVB", file: "datasheets/LVB.pdf" }, { label: "דף נתונים — LVB", file: "datasheets/DS_LVB.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "LVB500": [{ label: "דף קטלוגי — LVB", file: "datasheets/LVB.pdf" }, { label: "דף נתונים — LVB", file: "datasheets/DS_LVB.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "LVB700": [{ label: "דף קטלוגי — LVB", file: "datasheets/LVB.pdf" }, { label: "דף נתונים — LVB", file: "datasheets/DS_LVB.pdf" }],
  "LVJ": [{ label: "דף קטלוגי — LV", file: "datasheets/LV.pdf" }, { label: "דף נתונים — LV", file: "datasheets/DS_LV.pdf" }],
  "LVL": [{ label: "דף קטלוגי — LV2", file: "datasheets/LV2.pdf" }, { label: "דף נתונים — LV2", file: "datasheets/DS_LV2.pdf" }],
  "LVP": [{ label: "דף קטלוגי — LV2", file: "datasheets/LV2.pdf" }, { label: "דף נתונים — LV2", file: "datasheets/DS_LV2.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "LVQ": [{ label: "דף קטלוגי — LV2", file: "datasheets/LV2.pdf" }, { label: "דף נתונים — LV2", file: "datasheets/DS_LV2.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "LVX": [{ label: "דף קטלוגי — LV", file: "datasheets/LV.pdf" }, { label: "דף נתונים — LV", file: "datasheets/DS_LV.pdf" }],
  "LVXRGB": [{ label: "דף קטלוגי — LVXRGB", file: "datasheets/LVXRGB.pdf" }, { label: "דף נתונים — LVXRGB", file: "datasheets/DS_LVXRGB.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "LVY": [{ label: "דף קטלוגי — LV", file: "datasheets/LV.pdf" }, { label: "דף נתונים — LV", file: "datasheets/DS_LV.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "LVZ": [{ label: "דף קטלוגי — LV", file: "datasheets/LV.pdf" }, { label: "דף נתונים — LV", file: "datasheets/DS_LV.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "MD100": [{ label: "דף קטלוגי — MD", file: "datasheets/MD.pdf" }, { label: "דף נתונים — MD", file: "datasheets/DS_MD.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "MD48320 48V": [{ label: "דף קטלוגי — MD48320", file: "datasheets/MD48320.pdf" }, { label: "דף נתונים — MD48320", file: "datasheets/DS_MD48320.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_MD320.pdf" }],
  "MDE030 DIMMABLE": [{ label: "דף קטלוגי — MDE", file: "datasheets/MDE.pdf" }, { label: "דף נתונים — MDE", file: "datasheets/DS_MDE.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori dimmerabili.pdf" }],
  "PBT100 DIMMABLE": [{ label: "דף קטלוגי — PBT", file: "datasheets/PBT.pdf" }, { label: "דף נתונים — PBT", file: "datasheets/DS_PBT.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_PBT.pdf" }],
  "MDR45 DIMMABLE": [{ label: "דף קטלוגי — MDR", file: "datasheets/MDR.pdf" }, { label: "דף נתונים — MDR", file: "datasheets/DS_MDR.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_MDR.pdf" }],
  "MDR60 DIMMABLE": [{ label: "דף קטלוגי — MDR", file: "datasheets/MDR.pdf" }, { label: "דף נתונים — MDR", file: "datasheets/DS_MDR.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_MDR.pdf" }],
  "MINI TRACK M18": [{ label: "דף קטלוגי — TRACKM", file: "datasheets/TRACKM.pdf" }, { label: "דף נתונים — TRACKM", file: "datasheets/DS_TRACKM.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_TRACKM.pdf" }],
  "MINI TRACK M18D": [{ label: "דף קטלוגי — TRACKMD", file: "datasheets/TRACKMD.pdf" }, { label: "דף נתונים — TRACKMD", file: "datasheets/DS_TRACKMD.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_TRACKMD.pdf" }],
  "MINI TRACK M33": [{ label: "דף קטלוגי — TRACKM", file: "datasheets/TRACKM.pdf" }, { label: "דף נתונים — TRACKM", file: "datasheets/DS_TRACKM.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_TRACKM.pdf" }],
  "MININICE3": [{ label: "דף קטלוגי — MN", file: "datasheets/MN.pdf" }, { label: "דף נתונים — MN", file: "datasheets/DS_MN.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "MININICE4": [{ label: "דף קטלוגי — MN", file: "datasheets/MN.pdf" }, { label: "דף נתונים — MN", file: "datasheets/DS_MN.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "MININICE5": [{ label: "דף קטלוגי — MN", file: "datasheets/MN.pdf" }, { label: "דף נתונים — MN", file: "datasheets/DS_MN.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "MIP054": [{ label: "דף קטלוגי — MIP", file: "datasheets/MIP.pdf" }, { label: "דף נתונים — MIP", file: "datasheets/DS_MIP.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "MIP070": [{ label: "דף קטלוגי — MIP", file: "datasheets/MIP.pdf" }, { label: "דף נתונים — MIP", file: "datasheets/DS_MIP.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "MIP110": [{ label: "דף קטלוגי — MIP", file: "datasheets/MIP.pdf" }, { label: "דף נתונים — MIP", file: "datasheets/DS_MIP.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "MIP160": [{ label: "דף קטלוגי — MIP", file: "datasheets/MIP.pdf" }, { label: "דף נתונים — MIP", file: "datasheets/DS_MIP.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "MPI1": [{ label: "דף קטלוגי — MPL MPI", file: "datasheets/MPL_MPI.pdf" }, { label: "דף נתונים — MPI", file: "datasheets/DS_MPI.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_MPI.pdf" }],
  "MPI3": [{ label: "דף קטלוגי — MPL MPI", file: "datasheets/MPL_MPI.pdf" }, { label: "דף נתונים — MPI", file: "datasheets/DS_MPI.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_MPI.pdf" }],
  "MPI4": [{ label: "דף קטלוגי — MPL MPI", file: "datasheets/MPL_MPI.pdf" }, { label: "דף נתונים — MPI", file: "datasheets/DS_MPI.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_MPI.pdf" }],
  "MPL1": [{ label: "דף קטלוגי — MPL MPI", file: "datasheets/MPL_MPI.pdf" }, { label: "דף נתונים — MPL", file: "datasheets/DS_MPL.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "MPL3": [{ label: "דף קטלוגי — MPL MPI", file: "datasheets/MPL_MPI.pdf" }, { label: "דף נתונים — MPL", file: "datasheets/DS_MPL.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "MPL4": [{ label: "דף קטלוגי — MPL MPI", file: "datasheets/MPL_MPI.pdf" }, { label: "דף נתונים — MPL", file: "datasheets/DS_MPL.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "MPL5": [{ label: "דף קטלוגי — MPL MPI", file: "datasheets/MPL_MPI.pdf" }, { label: "דף נתונים — MPL", file: "datasheets/DS_MPL.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "MT30 LED": [{ label: "דף קטלוגי — MTLED", file: "datasheets/MTLED.pdf" }, { label: "דף נתונים — MTLED", file: "datasheets/DS_MTLED.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_MTLED_TLF.pdf" }],
  "NICE110": [{ label: "דף קטלוגי — NICE", file: "datasheets/NICE.pdf" }, { label: "דף נתונים — NICE", file: "datasheets/DS_NICE.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "NICE206": [{ label: "דף קטלוגי — NICE", file: "datasheets/NICE.pdf" }, { label: "דף נתונים — NICE", file: "datasheets/DS_NICE.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "NICE303": [{ label: "דף קטלוגי — NICE", file: "datasheets/NICE.pdf" }, { label: "דף נתונים — NICE", file: "datasheets/DS_NICE.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "NIP109": [{ label: "דף קטלוגי — NIP", file: "datasheets/NIP.pdf" }, { label: "דף נתונים — NIP", file: "datasheets/DS_NIP.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "NIP206": [{ label: "דף קטלוגי — NIP", file: "datasheets/NIP.pdf" }, { label: "דף נתונים — NIP", file: "datasheets/DS_NIP.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "NIP303": [{ label: "דף קטלוגי — NIP", file: "datasheets/NIP.pdf" }, { label: "דף נתונים — NIP", file: "datasheets/DS_NIP.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "PBF060": [{ label: "דף קטלוגי — PBF", file: "datasheets/PBF.pdf" }, { label: "דף נתונים — PBF", file: "datasheets/DS_PBF.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "PBF060D DIMMABLE": [{ label: "דף קטלוגי — PBFD", file: "datasheets/PBFD.pdf" }, { label: "דף נתונים — PBFD", file: "datasheets/DS_PBFD.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_PBFD.pdf" }],
  "PBF075": [{ label: "דף קטלוגי — PBF", file: "datasheets/PBF.pdf" }, { label: "דף נתונים — PBF", file: "datasheets/DS_PBF.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "PBF075D DIMMABLE": [{ label: "דף קטלוגי — PBFD", file: "datasheets/PBFD.pdf" }, { label: "דף נתונים — PBFD", file: "datasheets/DS_PBFD.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_PBFD.pdf" }],
  "PBF100": [{ label: "דף קטלוגי — PBF", file: "datasheets/PBF.pdf" }, { label: "דף נתונים — PBF", file: "datasheets/DS_PBF.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "PBF100D DIMMABLE": [{ label: "דף קטלוגי — PBFD", file: "datasheets/PBFD.pdf" }, { label: "דף נתונים — PBFD", file: "datasheets/DS_PBFD.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_PBFD.pdf" }],
  "PBOX150": [{ label: "דף קטלוגי — PBOX", file: "datasheets/PBOX.pdf" }, { label: "דף נתונים — PBOX", file: "datasheets/DS_PBOX.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_PBOX_PBX.pdf" }],
  "PBOX35": [{ label: "דף קטלוגי — PBOX35", file: "datasheets/PBOX35.pdf" }, { label: "דף נתונים — PBOX35", file: "datasheets/DS_PBOX35.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "PBS060": [{ label: "דף קטלוגי — PBS", file: "datasheets/PBS.pdf" }, { label: "דף נתונים — PBS", file: "datasheets/DS_PBS.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_PBS.pdf" }],
  "PBS075": [{ label: "דף קטלוגי — PBS", file: "datasheets/PBS.pdf" }, { label: "דף נתונים — PBS", file: "datasheets/DS_PBS.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_PBS.pdf" }],
  "PBS075D DIMMABLE": [{ label: "דף קטלוגי — PBSD", file: "datasheets/PBSD.pdf" }, { label: "דף נתונים — PBSD", file: "datasheets/DS_PBSD.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_PBSD.pdf" }],
  "PBS100": [{ label: "דף קטלוגי — PBS", file: "datasheets/PBS.pdf" }, { label: "דף נתונים — PBS", file: "datasheets/DS_PBS.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_PBS.pdf" }],
  "PBS100D DIMMABLE": [{ label: "דף קטלוגי — PBSD", file: "datasheets/PBSD.pdf" }, { label: "דף נתונים — PBSD", file: "datasheets/DS_PBSD.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_PBSD.pdf" }],
  "PBT150 DIMMABLE": [{ label: "דף קטלוגי — PBT", file: "datasheets/PBT.pdf" }, { label: "דף נתונים — PBT", file: "datasheets/DS_PBT.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_PBT.pdf" }],
  "PBT200 DIMMABLE": [{ label: "דף קטלוגי — PBT200", file: "datasheets/PBT200.pdf" }, { label: "דף נתונים — PBT200", file: "datasheets/DS_PBT200.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_PBT.pdf" }],
  "PBX100": [{ label: "דף קטלוגי — PBX", file: "datasheets/PBX.pdf" }, { label: "דף נתונים — PBX", file: "datasheets/DS_PBX.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_PBOX_PBX.pdf" }],
  "PBX100D DIMMABLE": [{ label: "דף קטלוגי — PBXD", file: "datasheets/PBXD.pdf" }, { label: "דף נתונים — PBXD", file: "datasheets/DS_PBXD.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_PBXD.pdf" }],
  "PBX100TW": [{ label: "דף קטלוגי — PBXTW", file: "datasheets/PBXTW.pdf" }, { label: "דף נתונים — PBXTW", file: "datasheets/DS_PBXTW.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_PBXTW.pdf" }],
  "PBX10D48 DIMMABLE": [{ label: "דף קטלוגי — PBXD48", file: "datasheets/PBXD48.pdf" }, { label: "דף נתונים — PBXD48", file: "datasheets/DS_PBXD48.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_PBXD.pdf" }],
  "PBX150": [{ label: "דף קטלוגי — PBX", file: "datasheets/PBX.pdf" }, { label: "דף נתונים — PBX", file: "datasheets/DS_PBX.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_PBOX_PBX.pdf" }],
  "PBX15048": [{ label: "דף קטלוגי — PBX48", file: "datasheets/PBX48.pdf" }, { label: "דף נתונים — PBX48", file: "datasheets/DS_PBX48.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_PBOX_PBX.pdf" }],
  "PBX150D DIMMABLE": [{ label: "דף קטלוגי — PBXD", file: "datasheets/PBXD.pdf" }, { label: "דף נתונים — PBXD", file: "datasheets/DS_PBXD.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_PBXD.pdf" }],
  "PBX15D48 DIMMABLE": [{ label: "דף קטלוגי — PBXD48", file: "datasheets/PBXD48.pdf" }, { label: "דף נתונים — PBXD48", file: "datasheets/DS_PBXD48.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_PBXD.pdf" }],
  "PBX200": [{ label: "דף קטלוגי — PBX", file: "datasheets/PBX.pdf" }, { label: "דף נתונים — PBX", file: "datasheets/DS_PBX.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_PBOX_PBX.pdf" }],
  "PBX20048": [{ label: "דף קטלוגי — PBX48", file: "datasheets/PBX48.pdf" }, { label: "דף נתונים — PBX48", file: "datasheets/DS_PBX48.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_PBOX_PBX.pdf" }],
  "PBX7524D DIMMABLE": [{ label: "דף קטלוגי — PBXD", file: "datasheets/PBXD.pdf" }, { label: "דף נתונים — PBXD", file: "datasheets/DS_PBXD.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_PBXD.pdf" }],
  "PD312": [{ label: "דף קטלוגי — PD", file: "datasheets/PD.pdf" }, { label: "דף נתונים — PD", file: "datasheets/DS_PD.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "PDCVD DIMMABLE": [{ label: "דף קטלוגי — PDCVD", file: "datasheets/PDCVD.pdf" }, { label: "דף נתונים — PDCVD", file: "datasheets/DS_PDCVD.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_PDCVD_PDMCD.pdf" }],
  "PDLU RF INTERFACE": [{ label: "דף קטלוגי — PDLU", file: "datasheets/PDLU.pdf" }, { label: "דף נתונים — PDLU", file: "datasheets/DS_PDLU.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_PDLU_en.pdf" }],
  "PDLUSM SMART/RF INTERFACE": [{ label: "דף קטלוגי — PDLUSM", file: "datasheets/PDLUSM.pdf" }, { label: "דף נתונים — PDLUSM", file: "datasheets/DS_PDLUSM.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_PDLUSM_en.pdf" }],
  "PDMC MULTICURRENT": [{ label: "דף קטלוגי — PDMC", file: "datasheets/PDMC.pdf" }, { label: "דף נתונים — PDMC", file: "datasheets/DS_PDMC.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "PDV24": [{ label: "דף קטלוגי — PDV", file: "datasheets/PDV.pdf" }, { label: "דף נתונים — PDV", file: "datasheets/DS_PDV.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "PLE060 DIMMABLE": [{ label: "דף קטלוגי — PLE", file: "datasheets/PLE.pdf" }, { label: "דף נתונים — PLE", file: "datasheets/DS_PLE.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "PLJ106": [{ label: "דף קטלוגי — PLR PLJ", file: "datasheets/PLR_PLJ.pdf" }, { label: "דף נתונים — PLR PLJ", file: "datasheets/DS_PLR_PLJ.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "PLJ110": [{ label: "דף קטלוגי — PLR PLJ", file: "datasheets/PLR_PLJ.pdf" }, { label: "דף נתונים — PLR PLJ", file: "datasheets/DS_PLR_PLJ.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "PLJ204": [{ label: "דף קטלוגי — PLR PLJ", file: "datasheets/PLR_PLJ.pdf" }, { label: "דף נתונים — PLR PLJ", file: "datasheets/DS_PLR_PLJ.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "PLJ303": [{ label: "דף קטלוגי — PLR PLJ", file: "datasheets/PLR_PLJ.pdf" }, { label: "דף נתונים — PLR PLJ", file: "datasheets/DS_PLR_PLJ.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "PLK110Z": [{ label: "דף קטלוגי — PLK", file: "datasheets/PLK.pdf" }, { label: "דף נתונים — PLK", file: "datasheets/DS_PLK.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "PLK112": [{ label: "דף קטלוגי — PLK", file: "datasheets/PLK.pdf" }, { label: "דף נתונים — PLK", file: "datasheets/DS_PLK.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "PLK113": [{ label: "דף קטלוגי — PLK", file: "datasheets/PLK.pdf" }, { label: "דף נתונים — PLK", file: "datasheets/DS_PLK.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "PLK12": [{ label: "דף קטלוגי — PLK", file: "datasheets/PLK.pdf" }, { label: "דף נתונים — PLK", file: "datasheets/DS_PLK.pdf" }],
  "PLK185": [{ label: "דף קטלוגי — PLK", file: "datasheets/PLK.pdf" }, { label: "דף נתונים — PLK", file: "datasheets/DS_PLK.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "PLK205": [{ label: "דף קטלוגי — PLK", file: "datasheets/PLK.pdf" }, { label: "דף נתונים — PLK", file: "datasheets/DS_PLK.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "PLK300": [{ label: "דף קטלוגי — PLK", file: "datasheets/PLK.pdf" }, { label: "דף נתונים — PLK", file: "datasheets/DS_PLK.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "PLK306": [{ label: "דף קטלוגי — PLK", file: "datasheets/PLK.pdf" }, { label: "דף נתונים — PLK", file: "datasheets/DS_PLK.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "PLKE109 DIMMABLE": [{ label: "דף קטלוגי — PLKE", file: "datasheets/PLKE.pdf" }, { label: "דף נתונים — PLKE", file: "datasheets/DS_PLKE.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori dimmerabili.pdf" }],
  "PLKE109": [{ label: "דף קטלוגי — PLKE", file: "datasheets/PLKE.pdf" }, { label: "דף נתונים — PLKE", file: "datasheets/DS_PLKE.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori dimmerabili.pdf" }],
  "PLKE205 DIMMABLE": [{ label: "דף קטלוגי — PLKE", file: "datasheets/PLKE.pdf" }, { label: "דף נתונים — PLKE", file: "datasheets/DS_PLKE.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori dimmerabili.pdf" }],
  "PLKE24 DIMMABLE": [{ label: "דף קטלוגי — PLKE", file: "datasheets/PLKE.pdf" }, { label: "דף נתונים — PLKE", file: "datasheets/DS_PLKE.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "PLKE306 DIMMABLE": [{ label: "דף קטלוגי — PLKE", file: "datasheets/PLKE.pdf" }, { label: "דף נתונים — PLKE", file: "datasheets/DS_PLKE.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori dimmerabili.pdf" }],
  "PLP105N": [{ label: "דף קטלוגי — PLP", file: "datasheets/PLP.pdf" }, { label: "דף נתונים — PLP", file: "datasheets/DS_PLP.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "PLP105T": [{ label: "דף קטלוגי — PLP", file: "datasheets/PLP.pdf" }, { label: "דף נתונים — PLP", file: "datasheets/DS_PLP.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "PLP106N": [{ label: "דף קטלוגי — PLP", file: "datasheets/PLP.pdf" }, { label: "דף נתונים — PLP", file: "datasheets/DS_PLP.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "PLP106T": [{ label: "דף קטלוגי — PLP", file: "datasheets/PLP.pdf" }, { label: "דף נתונים — PLP", file: "datasheets/DS_PLP.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "PLP112N": [{ label: "דף קטלוגי — PLP", file: "datasheets/PLP.pdf" }, { label: "דף נתונים — PLP", file: "datasheets/DS_PLP.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "PLP112T": [{ label: "דף קטלוגי — PLP", file: "datasheets/PLP.pdf" }, { label: "דף נתונים — PLP", file: "datasheets/DS_PLP.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "PLP12N": [{ label: "דף קטלוגי — PLP", file: "datasheets/PLP.pdf" }, { label: "דף נתונים — PLP", file: "datasheets/DS_PLP.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "PLP12T": [{ label: "דף קטלוגי — PLP", file: "datasheets/PLP.pdf" }, { label: "דף נתונים — PLP", file: "datasheets/DS_PLP.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "PLP303N": [{ label: "דף קטלוגי — PLP", file: "datasheets/PLP.pdf" }, { label: "דף נתונים — PLP", file: "datasheets/DS_PLP.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "PLP303T": [{ label: "דף קטלוגי — PLP", file: "datasheets/PLP.pdf" }, { label: "דף נתונים — PLP", file: "datasheets/DS_PLP.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "PLP306N": [{ label: "דף קטלוגי — PLP", file: "datasheets/PLP.pdf" }, { label: "דף נתונים — PLP", file: "datasheets/DS_PLP.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "PLP306T": [{ label: "דף קטלוגי — PLP", file: "datasheets/PLP.pdf" }, { label: "דף נתונים — PLP", file: "datasheets/DS_PLP.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "PLR106": [{ label: "דף קטלוגי — PLR PLJ", file: "datasheets/PLR_PLJ.pdf" }, { label: "דף נתונים — PLR PLJ", file: "datasheets/DS_PLR_PLJ.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "PLR110": [{ label: "דף קטלוגי — PLR PLJ", file: "datasheets/PLR_PLJ.pdf" }, { label: "דף נתונים — PLR PLJ", file: "datasheets/DS_PLR_PLJ.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "PLR204": [{ label: "דף קטלוגי — PLR PLJ", file: "datasheets/PLR_PLJ.pdf" }, { label: "דף נתונים — PLR PLJ", file: "datasheets/DS_PLR_PLJ.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "PLR303": [{ label: "דף קטלוגי — PLR PLJ", file: "datasheets/PLR_PLJ.pdf" }, { label: "דף נתונים — PLR PLJ", file: "datasheets/DS_PLR_PLJ.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "PLV050": [{ label: "דף קטלוגי — PLV", file: "datasheets/PLV.pdf" }, { label: "דף נתונים — PLV", file: "datasheets/DS_PLV.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "PLV100": [{ label: "דף קטלוגי — PLV", file: "datasheets/PLV.pdf" }, { label: "דף נתונים — PLV", file: "datasheets/DS_PLV.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "PLV10048": [{ label: "דף קטלוגי — PLV48", file: "datasheets/PLV48.pdf" }, { label: "דף נתונים — PLV48", file: "datasheets/DS_PLV48.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "PLV150": [{ label: "דף קטלוגי — PLV", file: "datasheets/PLV.pdf" }, { label: "דף נתונים — PLV", file: "datasheets/DS_PLV.pdf" }],
  "PLV15048": [{ label: "דף קטלוגי — PLV48", file: "datasheets/PLV48.pdf" }, { label: "דף נתונים — PLV48", file: "datasheets/DS_PLV48.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "PLV300": [{ label: "דף קטלוגי — PLV300", file: "datasheets/PLV300.pdf" }, { label: "דף נתונים — PLV300", file: "datasheets/DS_PLV300.pdf" }],
  "PLV300D  DALI/PUSH": [{ label: "דף קטלוגי — PLVD", file: "datasheets/PLVD.pdf" }, { label: "דף נתונים — PLVD", file: "datasheets/DS_PLVD.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_PLVD.pdf" }],
  "PLZ140": [{ label: "דף קטלוגי — PLZ RLZ", file: "datasheets/PLZ_RLZ.pdf" }, { label: "דף נתונים — PLZ RLZ", file: "datasheets/DS_PLZ_RLZ.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "PLZ350": [{ label: "דף קטלוגי — PLZ RLZ", file: "datasheets/PLZ_RLZ.pdf" }, { label: "דף נתונים — PLZ RLZ", file: "datasheets/DS_PLZ_RLZ.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "PLZ400": [{ label: "דף קטלוגי — PLZ RLZ", file: "datasheets/PLZ_RLZ.pdf" }, { label: "דף נתונים — PLZ RLZ", file: "datasheets/DS_PLZ_RLZ.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "PLZ500": [{ label: "דף קטלוגי — PLZ RLZ", file: "datasheets/PLZ_RLZ.pdf" }, { label: "דף נתונים — PLZ RLZ", file: "datasheets/DS_PLZ_RLZ.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "PRL12": [{ label: "דף קטלוגי — PRL", file: "datasheets/PRL.pdf" }, { label: "דף נתונים — PRL", file: "datasheets/DS_PRL.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "PRL185": [{ label: "דף קטלוגי — PRL", file: "datasheets/PRL.pdf" }, { label: "דף נתונים — PRL", file: "datasheets/DS_PRL.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "PRL300": [{ label: "דף קטלוגי — PRL", file: "datasheets/PRL.pdf" }, { label: "דף נתונים — PRL", file: "datasheets/DS_PRL.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "PTEMC24 MULTICURRENT DIMMABLE": [{ label: "דף קטלוגי — PTE", file: "datasheets/PTE.pdf" }, { label: "דף נתונים — PTE", file: "datasheets/DS_PTE.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori dimmerabili.pdf" }],
  "PUL42BB MULTICURRENT DIMMABLE": [{ label: "דף קטלוגי — PUL", file: "datasheets/PUL.pdf" }, { label: "דף נתונים — PUL", file: "datasheets/DS_PUL.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_PUL.pdf" }],
  "PUL42BE MULTICURRENT DIMMABLE": [{ label: "דף קטלוגי — PUL", file: "datasheets/PUL.pdf" }, { label: "דף נתונים — PUL", file: "datasheets/DS_PUL.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_PUL.pdf" }],
  "PUL60AB MULTICURRENT DIMMABLE": [{ label: "דף קטלוגי — PUL", file: "datasheets/PUL.pdf" }, { label: "דף נתונים — PUL", file: "datasheets/DS_PUL.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_PUL.pdf" }],
  "PUL60AE MULTICURRENT DIMMABLE": [{ label: "דף קטלוגי — PUL", file: "datasheets/PUL.pdf" }, { label: "דף נתונים — PUL", file: "datasheets/DS_PUL.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_PUL.pdf" }],
  "PWM REPEATER 4channels": [{ label: "דף קטלוגי — PWMREP4", file: "datasheets/PWMREP4.pdf" }, { label: "דף נתונים — PWMREP4", file: "datasheets/DS_PWMREP4.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_PWMREP4.pdf" }],
  "QBOX MULTICURRENT": [{ label: "דף קטלוגי — QBOX", file: "datasheets/QBOX.pdf" }, { label: "דף נתונים — QBOX", file: "datasheets/DS_QBOX.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_QBOX.pdf" }],
  "QBOX110 MULTICURRENT 1": [{ label: "דף קטלוגי — QBOX110", file: "datasheets/QBOX110.pdf" }, { label: "דף נתונים — QBOX110", file: "datasheets/DS_QBOX110.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_QBOX.pdf" }],
  "RC309": [{ label: "דף קטלוגי — RC RP", file: "datasheets/RC_RP.pdf" }, { label: "דף נתונים — RC RP", file: "datasheets/DS_RC_RP.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "RC312": [{ label: "דף קטלוגי — RC RP", file: "datasheets/RC_RP.pdf" }, { label: "דף נתונים — RC RP", file: "datasheets/DS_RC_RP.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "RC315": [{ label: "דף קטלוגי — RC RP", file: "datasheets/RC_RP.pdf" }, { label: "דף נתונים — RC RP", file: "datasheets/DS_RC_RP.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "RCC TW CC": [{ label: "דף קטלוגי — RCCTW", file: "datasheets/RCCTW.pdf" }, { label: "דף נתונים — RCCTW", file: "datasheets/DS_RCCTW.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_RCCTW.pdf" }],
  "RCDIMCT RF TRANSMITTER": [{ label: "דף קטלוגי — RC", file: "datasheets/RC.pdf" }, { label: "דף נתונים — RC", file: "datasheets/DS_RC.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_RC.pdf" }],
  "RCRGBW RF TRANSMITTER": [{ label: "דף קטלוגי — RC", file: "datasheets/RC.pdf" }, { label: "דף נתונים — RC", file: "datasheets/DS_RC.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_RC.pdf" }],
  "RGBOX35 RGB": [{ label: "דף קטלוגי — RGBOX35", file: "datasheets/RGBOX35.pdf" }, { label: "דף נתונים — RGBOX35", file: "datasheets/DS_RGBOX35.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_RGBOX35.pdf" }],
  "RGBOX412 RGB": [{ label: "דף קטלוגי — RGBOX412", file: "datasheets/RGBOX412.pdf" }, { label: "דף נתונים — RGBOX4", file: "datasheets/DS_RGBOX4.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_RGBOX4.pdf" }],
  "RGBOX435 RGB+W CC": [{ label: "דף קטלוגי — RGBOX435", file: "datasheets/RGBOX435.pdf" }, { label: "דף נתונים — RGBOX435", file: "datasheets/DS_RGBOX435.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_RGBOX435.pdf" }],
  "RGBOX45 RGB": [{ label: "דף קטלוגי — RGBOX45 55", file: "datasheets/RGBOX45_55.pdf" }, { label: "דף נתונים — RGBOX45 55", file: "datasheets/DS_RGBOX45_55.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_RGBOX45_55.pdf" }],
  "RGBOX55 RGB": [{ label: "דף קטלוגי — RGBOX45 55", file: "datasheets/RGBOX45_55.pdf" }, { label: "דף נתונים — RGBOX45 55", file: "datasheets/DS_RGBOX45_55.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_RGBOX45_55.pdf" }],
  "RLZ140": [{ label: "דף קטלוגי — PLZ RLZ", file: "datasheets/PLZ_RLZ.pdf" }, { label: "דף נתונים — PLZ RLZ", file: "datasheets/DS_PLZ_RLZ.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "RLZ350": [{ label: "דף קטלוגי — PLZ RLZ", file: "datasheets/PLZ_RLZ.pdf" }, { label: "דף נתונים — PLZ RLZ", file: "datasheets/DS_PLZ_RLZ.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "RLZ400": [{ label: "דף קטלוגי — PLZ RLZ", file: "datasheets/PLZ_RLZ.pdf" }, { label: "דף נתונים — PLZ RLZ", file: "datasheets/DS_PLZ_RLZ.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "RLZ500": [{ label: "דף קטלוגי — PLZ RLZ", file: "datasheets/PLZ_RLZ.pdf" }, { label: "דף נתונים — PLZ RLZ", file: "datasheets/DS_PLZ_RLZ.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "RLZ640": [{ label: "דף קטלוגי — PLZ RLZ", file: "datasheets/PLZ_RLZ.pdf" }, { label: "דף נתונים — PLZ RLZ", file: "datasheets/DS_PLZ_RLZ.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "RP309": [{ label: "דף קטלוגי — RC RP", file: "datasheets/RC_RP.pdf" }, { label: "דף נתונים — RC RP", file: "datasheets/DS_RC_RP.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "RP312": [{ label: "דף קטלוגי — RC RP", file: "datasheets/RC_RP.pdf" }, { label: "דף נתונים — RC RP", file: "datasheets/DS_RC_RP.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "RP315": [{ label: "דף קטלוגי — RC RP", file: "datasheets/RC_RP.pdf" }, { label: "דף נתונים — RC RP", file: "datasheets/DS_RC_RP.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "SC42 TRACK  CC  ON/OFF": [{ label: "דף קטלוגי — SC ONOFF", file: "datasheets/SC_ONOFF.pdf" }, { label: "דף נתונים — SC ONOFF", file: "datasheets/DS_SC_ONOFF.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_SC_ONOFF.pdf" }],
  "SL24045 Slim 24V": [{ label: "דף קטלוגי — SL24", file: "datasheets/SL24.pdf" }, { label: "דף נתונים — SL24", file: "datasheets/DS_SL24.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_SL24.pdf" }],
  "SL24075 Slim 24V": [{ label: "דף קטלוגי — SL24", file: "datasheets/SL24.pdf" }, { label: "דף נתונים — SL24", file: "datasheets/DS_SL24.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_SL24.pdf" }],
  "SL24100 Slim 24V": [{ label: "דף קטלוגי — SL24", file: "datasheets/SL24.pdf" }, { label: "דף נתונים — SL24", file: "datasheets/DS_SL24.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_SL24.pdf" }],
  "SL24150 Slim 24V": [{ label: "דף קטלוגי — SL24", file: "datasheets/SL24.pdf" }, { label: "דף נתונים — SL24", file: "datasheets/DS_SL24.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_SL24.pdf" }],
  "SL24200 Slim 24V": [{ label: "דף קטלוגי — SL24", file: "datasheets/SL24.pdf" }, { label: "דף נתונים — SL24", file: "datasheets/DS_SL24.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_SL24.pdf" }],
  "SL2435": [{ label: "דף קטלוגי — SL", file: "datasheets/SL.pdf" }, { label: "דף נתונים — SL", file: "datasheets/DS_SL.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_Alimentatori.pdf" }],
  "SLIMBOX100": [{ label: "דף קטלוגי — SLBOX", file: "datasheets/SLBOX.pdf" }, { label: "דף נתונים — SLIMBOX", file: "datasheets/DS_SLIMBOX.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_SLBOX.pdf" }],
  "SLIMBOX60": [{ label: "דף קטלוגי — SLBOX", file: "datasheets/SLBOX.pdf" }, { label: "דף נתונים — SLIMBOX", file: "datasheets/DS_SLIMBOX.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_SLBOX.pdf" }],
  "SLIMBOX60 1": [{ label: "דף קטלוגי — SLBOXD", file: "datasheets/SLBOXD.pdf" }, { label: "דף נתונים — SLBOXD", file: "datasheets/DS_SLBOXD.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_SLBOX.pdf" }],
  "SPI03": [{ label: "דף קטלוגי — SPI03", file: "datasheets/SPI03.pdf" }, { label: "דף נתונים — SPI03", file: "datasheets/DS_SPI03.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_SPI03_PT.pdf" }],
  "TH24012 Thin 24V": [{ label: "דף קטלוגי — TH24012 TH24030", file: "datasheets/TH24012_TH24030.pdf" }, { label: "דף נתונים — TH24012 TH24030", file: "datasheets/DS_TH24012_TH24030.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_TH.pdf" }],
  "TH24020 Thin 24V": [{ label: "דף קטלוגי — TH12 24", file: "datasheets/TH12_24.pdf" }, { label: "דף נתונים — TH12 24", file: "datasheets/DS_TH12_24.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_TH.pdf" }],
  "TH24030U Thin UL 24V": [{ label: "דף קטלוגי — TH UL", file: "datasheets/TH UL.pdf" }, { label: "דף נתונים — TH UL", file: "datasheets/DS_TH UL.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_THUL.pdf" }],
  "TOP LF": [{ label: "דף קטלוגי — TLF", file: "datasheets/TLF.pdf" }, { label: "דף נתונים — TLF", file: "datasheets/DS_TLF.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_MTLED_TLF.pdf" }],
  "TRACK28": [{ label: "דף קטלוגי — TRACK", file: "datasheets/TRACK.pdf" }, { label: "דף נתונים — TRACK28 29", file: "datasheets/DS_TRACK28_29.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_TRACK28_29.pdf" }],
  "TRACK29": [{ label: "דף קטלוגי — TRACK", file: "datasheets/TRACK.pdf" }, { label: "דף נתונים — TRACK28 29", file: "datasheets/DS_TRACK28_29.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_TRACK28_29.pdf" }],
  "WALL CT2": [{ label: "דף קטלוגי — WALL", file: "datasheets/WALL.pdf" }, { label: "דף נתונים — WALL", file: "datasheets/DS_WALL.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_WALL.pdf" }],
  "WALL DIM2": [{ label: "דף קטלוגי — WALL", file: "datasheets/WALL.pdf" }, { label: "דף נתונים — WALL", file: "datasheets/DS_WALL.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_WALL.pdf" }],
  "WALL RGB2": [{ label: "דף קטלוגי — WALL", file: "datasheets/WALL.pdf" }, { label: "דף נתונים — WALL", file: "datasheets/DS_WALL.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_WALL.pdf" }],
  "WALL RGBW": [{ label: "דף קטלוגי — WALL", file: "datasheets/WALL.pdf" }, { label: "דף נתונים — WALL", file: "datasheets/DS_WALL.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_WALL.pdf" }],
  "WALLWP86K": [{ label: "דף קטלוגי — WALLWP86K", file: "datasheets/WALLWP86K.pdf" }, { label: "דף נתונים — WALLWP86K", file: "datasheets/DS_WALLWP86K.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_WALLWP86K_PT.pdf" }],
  "ZBDALI INTERFACE ZIGBEE/BLE a DALI": [{ label: "דף קטלוגי — ZBDALI", file: "datasheets/ZBDALI.pdf" }, { label: "דף נתונים — ZBDALI", file: "datasheets/DS_ZBDALI.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_ZBDALI.pdf" }],
  "ZBX100 ALIMENTATORE ZIGBEE/BLE/PUSH": [{ label: "דף קטלוגי — ZBX", file: "datasheets/ZBX.pdf" }, { label: "דף נתונים — ZBX", file: "datasheets/DS_ZBX.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_ZBX.pdf" }],
  "ZBX10048 ALIMENTATORE ZIGBEE/BLE/PUSH": [{ label: "דף קטלוגי — ZBX", file: "datasheets/ZBX.pdf" }, { label: "דף נתונים — ZBX", file: "datasheets/DS_ZBX.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_ZBX.pdf" }],
  "ZBX150 ALIMENTATORE ZIGBEE/BLE/PUSH": [{ label: "דף קטלוגי — ZBX", file: "datasheets/ZBX.pdf" }, { label: "דף נתונים — ZBX", file: "datasheets/DS_ZBX.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_ZBX.pdf" }],
  "ZCCBXH60 MULTICURRENT ZIGBEE/BLE/PUSH": [{ label: "דף קטלוגי — ZCCBX", file: "datasheets/ZCCBX.pdf" }, { label: "דף נתונים — ZCCBX", file: "datasheets/DS_ZCCBX.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_ZCCBX.pdf" }],
  "ZCCBXL60 MULTICURRENT ZIGBEE/BLE/PUSH": [{ label: "דף קטלוגי — ZCCBX", file: "datasheets/ZCCBX.pdf" }, { label: "דף נתונים — ZCCBX", file: "datasheets/DS_ZCCBX.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_ZCCBX.pdf" }],
  "ZCUBE24 INTERFACE 24V ZIGBEE/BLE/PUSH": [{ label: "דף קטלוגי — ZCUBE", file: "datasheets/ZCUBE.pdf" }, { label: "דף נתונים — ZCUBE", file: "datasheets/DS_ZCUBE.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_ZCUBE.pdf" }],
  "ZCUBE48 INTERFACE 48V ZIGBEE/BLE/PUSH": [{ label: "דף קטלוגי — ZCUBE", file: "datasheets/ZCUBE.pdf" }, { label: "דף נתונים — ZCUBE", file: "datasheets/DS_ZCUBE.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_ZCUBE.pdf" }],
  "ZIPB INTERFACE 12/24V ZIGBEE/BLE/PUSH": [{ label: "דף קטלוגי — ZIPB", file: "datasheets/ZIPB.pdf" }, { label: "דף נתונים — ZIPB", file: "datasheets/DS_ZIPB.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_ZIPB.pdf" }],
  "ZIDLK INTERFACE ZIGBEE/BLE a DALI": [{ label: "דף קטלוגי — ZIDLK", file: "datasheets/ZIDLK.pdf" }, { label: "דף נתונים — ZIDLK", file: "datasheets/DS_ZIDLK.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_ZIDLK.pdf" }],
  "ZMC013 MULTICURRENT ZIGBEE/BLE/PUSH": [{ label: "דף קטלוגי — ZMC013", file: "datasheets/ZMC013.pdf" }, { label: "דף נתונים — ZMC13", file: "datasheets/DS_ZMC13.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_ZMC13.pdf" }],
  "ZPB4 INTERFACE 4": [{ label: "דף קטלוגי — ZPB4", file: "datasheets/ZPB4.pdf" }, { label: "דף נתונים — ZPB4", file: "datasheets/DS_ZPB4.pdf" }, { label: "הוראות הפעלה", file: "datasheets/I_ZPB4.pdf" }],
};
